name: Deploy Sample Data to S3 mirror
on:
  push:
    branches:
      - main
jobs:
  run:
    name: Upload Data to S3
    runs-on: ubuntu-latest
    if: github.repository == 'sunpy/data'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
        - uses: actions/checkout@v4
          with:
            lfs: true

        - name: Generate Indices
          run: |
            ls
            ls sunpy/v1/
            bash generate_index.sh > index.html


        - name: Deploy
          uses: reggionick/s3-deploy@v4
          with:
            folder: ./
            bucket: data.sunpy.org
            bucket-region: "eu-west-1"
            delete-removed: true
